### ISSUE TITLE
Source different from binaries to github

### ISSUE THREAD

**Issue by chuckdee68** [reliak/moonpdf#10]
The source contained in this repository is different from the source where the code requests that we download the binaries from, i.e. on sourceforge at https://sourceforge.net/projects/moonpdf/files/.  Which should be considered the latest source?  Specifically for one example, the PdfLoaded event is FileLoaded at sourceforge.  I'm not sure if there are other changes.

From sourceforge source for MoonPdfPanel.xaml.cs

```
            if (this.FileLoaded != null)
                this.FileLoaded(this, EventArgs.Empty);
```

From [github](https://github.com/reliak/moonpdf/blob/master/src/MoonPdfLib/MoonPdfPanel.xaml.cs)

```
            if (this.PdfLoaded != null)
                this.PdfLoaded(this, EventArgs.Empty);

```

**Comment by reliak** [comment]
Hi,

sorry for the confusion. The latest source is here on Github: https://github.com/reliak/moonpdf/archive/master.zip

After adding the feature to also load PDFs from memory and not only from file, I renamed the event from `FileLoaded` to `PdfLoaded`.
