### ISSUE TITLE
App crashes during opening of a corrupted PDF file - Attempted to read or write protected memory

### ISSUE THREAD

**Issue by DominikPalo** [reliak/moonpdf#12]
When I try to load some corrupted pdf file, app crashes with an exception:

> Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
> 
> at MoonPdfLib.MuPdf.MuPdfWrapper.NativeMethods.CountPages(IntPtr doc)
> at MoonPdfLib.MuPdf.MuPdfWrapper.GetPageBounds(IPdfSource source, ImageRotation rotation, String password) at MoonPdfLib.MoonPdfPanel.LoadPdf(IPdfSource source, String password)
> at MoonPdfLib.MoonPdfPanel.Open(IPdfSource source, String password) 
> at MoonPdfLib.MoonPdfPanel.OpenFile(String pdfFilename, String password)

**Comment by reliak** [comment]
Well, if the PDF is corrupt, there is really nothing that MoonPdf could do instead of throwing an exception. Is this an unexpected behavior for you or what is the intention of this issue?

You can always use a try-catch-block in your calling code to prevent that your application crashes.

**Comment by DominikPalo** [comment]
Problem is that I cannot catch this exception (or I don't know how to do) - I decorated calling of the `MoonPdfPanel.OpenFile` method with try-catch, but exception is still not catched in this block and my app crashes. I think that is because exception comes from different app domain (from libmupdf.dll on calling the `CountPages` method imported from DLL)

**Comment by reliak** [comment]
You're right, the exception comes from the native libmupdf.dll. The exception handling from .NET 4.0 and above requires the Attribute `[HandleProcessCorruptedStateExceptions]` to catch native exceptions (see also http://stackoverflow.com/a/10517244/5604334).

If you put `[HandleProcessCorruptedStateExceptions]` on your calling method, you should be able to catch the native exception and handle it.

Please report if this solves your issue.

**Comment by DominikPalo** [comment]
Thank you! The `[HandleProcessCorruptedStateExceptions]` attribute helped and now it is possible to catch this exception. So I can implement handling of corrupted PDF's in my app.

**Comment by reliak** [comment]
Great, that's good to hear.
