### ISSUE TITLE
didnt add libmupdf.dll

### ISSUE THREAD

**Issue by bekirbostanci** [reliak/moonpdf#13]
i tried but i couldnt add dll.it give this error 
a reference to could not be added. please make sure that the file is accessible ...

How can i solve this problem

**Comment by netcore-jroger** [comment]
@aldehitdeveloper `libmupdf.dll` is a binary file and write by C++. just add it to your debug or release folder. The upper layer will call it as P/Invoke.

**Comment by bekirbostanci** [comment]
okey i will try 
thanks for answer :)

**Comment by bekirbostanci** [comment]
![2017-05-09_10-42-06](https://cloud.githubusercontent.com/assets/26343575/25840663/4c107d68-34a5-11e7-8600-6d2fb3a78c2a.png)

**Comment by netcore-jroger** [comment]
![qq 20170509155545](https://cloud.githubusercontent.com/assets/3223890/25840824/fc8d165e-34cf-11e7-8668-d42c531f27cd.png)

**Comment by netcore-jroger** [comment]
I think you need to watch the demo in the moonpdf repo.

**Comment by bekirbostanci** [comment]
can you send link for watching the demo

**Comment by netcore-jroger** [comment]
when I used  `moonpdf`, I watch this [article](http://www.codeproject.com/Articles/579878/MoonPdfPanel-A-WPF-based-PDF-Viewer-Control).

**Comment by 006Rain** [comment]
Yes. I download the project and try to build a new version with [ VS2013 + .Net FrameWork4.6.1 + x64 ]. It compiles with an error, like: " connot copy 'libmupdf.dll' from ... ". Then I new an subdir 'bin/MuLib/x64' in project folder, and put 'libmupdf.dll' in manually. It works.
Although it compiles very well, there still are some potential warnings, like: 
![image](https://user-images.githubusercontent.com/18030761/51015697-2f136500-15a8-11e9-9876-e93a8688c091.png)
I don't know what's this, but it dosen't matter to use it.
