### ISSUE TITLE
Print functionality

### ISSUE THREAD

**Issue by Krimsondk** [reliak/moonpdf#6]
Do you have any plans to add print functionality to the moonpdf library?

**Comment by reliak** [comment]
Currently I'm not adding any new functionality to moonpdf. But there is a post at codeproject in regard to printing, that might be helpful to you: http://www.codeproject.com/Messages/4711683/Re-Printing.aspx

**Comment by Krimsondk** [comment]
Thank you very much for your reply, which led me down the correct path to a working solution.

Thanks Again 😃

Fra: reliak
Sendt: ‎torsdag‎, ‎23‎. ‎oktober‎ ‎2014 ‎13‎:‎53
Til: reliak/moonpdf
Cc: Krimsondk

Currently I'm not adding any new functionality to moonpdf. But there is a post at codeproject in regard to printing, that might be helpful to you: http://www.codeproject.com/Messages/4711683/Re-Printing.aspx

**Comment by Joekraft** [comment]
Hi, the link no longer mentions any information about printing - any other solutions/examples?

**Comment by Mytza** [comment]
Hi,

You can find information about printing here:
http://www.codeproject.com/Articles/579878/MoonPdfPanel-A-WPF-based-PDF-Viewer-Control?fid=1830863&df=90&mpp=25&noise=3&prof=False&sort=Position&view=Normal&spc=Relaxed&fr=51#xx0xx

This uses winforms as a printdialog, i will post a solution using WPF MVVM and threading as soon as i have time.

Regards,
Mihai

**Comment by Joekraft** [comment]
WPF MVVM and threading sounds great, thanks Mytza!

**Comment by dmsergeev** [comment]
Seems like these comments were archived from codeproject. Can somebody post a wpf solution? Thanks
