### ISSUE TITLE
ZoomToFit 

### ISSUE THREAD

**Issue by marcoPolo84** [reliak/moonpdf#9]
Why there is no ZoomToFit Method ?

If the width is greater than height , call ZoomToWidth , otherwise ZoomToHeight .

Is possible to add this method ?

**Comment by reliak** [comment]
Sorry, this project is no longer maintained by me. You would need to do this check in your application, otherwise you could fork the repository and add these changes yourself.

**Comment by marcoPolo84** [comment]
Ok, thanks anyway.
Have a nice day

Date: Sat, 7 Nov 2015 08:11:19 -0800
